# -*- mode: ruby -*-
# vi: set ft=ruby :
#
Vagrant.require_version ">= 1.8.1"

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.


boxes = [
    {
        :name => "k8s-master",
        :enp0s8 => "192.168.205.10",
        :mem => "2048",
        :cpu => "2"
    },
    {
        :name => "k8s-worker1",
        :enp0s8 => "192.168.205.11",
        :mem => "4096",
        :cpu => "2"
    },
    {
        :name => "k8s-worker2",
        :enp0s8 => "192.168.205.12",
        :mem => "4096",
        :cpu => "2"
    }
]

Vagrant.configure(2) do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "ubuntu/xenial64"

  boxes.each do |opts|
      config.vm.define opts[:name] do |config|
        config.vm.hostname = opts[:name]

        config.vm.provider "virtualbox" do |v|
          v.customize ["modifyvm", :id, "--memory", opts[:mem]]
          v.customize ["modifyvm", :id, "--cpus", opts[:cpu]]
        end

        config.vm.network :private_network, ip: opts[:enp0s8], auto_config: true
        # For deploy k8s under proxy
        # if Vagrant.has_plugin?("vagrant-proxyconf")
        #   config.proxy.http     = "[Your proxy]"
        #   config.proxy.https    = "[Your proxy]"
        #   config.proxy.no_proxy = "localhost,127.0.0.1,192.168.205.0/24"
        # end
      end
  end
  config.vm.provision "shell", inline: <<-SHELL
    # Config proxy
    # sudo mkdir -p /etc/systemd/system/docker.service.d
    # echo '[Service]' >> http_proxy.conf
    # echo 'Environment="HTTP_PROXY=[Your proxy]"' >> http_proxy.conf
    # sudo mv http_proxy.conf /etc/systemd/system/docker.service.d
    # echo 'Acquire::http::proxy "[Your proxy]";' >> apt.conf
    # echo 'Acquire::https::proxy "[Your proxy]";' >> apt.conf
    # sudo mv apt.conf /etc/apt/
    echo "deb http://apt.kubernetes.io/ kubernetes-xenial main" >> ~/kubernetes.list
    sudo mv ~/kubernetes.list /etc/apt/sources.list.d
    sudo apt-get update
    # Install docker if you don't have it already.
    sudo apt-get install -y docker.io
    apt-get install -y kubelet kubeadm kubectl kubernetes-cni --allow-unauthenticated
  SHELL
end
