Vagrant.configure("2") do |config|

  config.vm.define "bgp-router" do |router|
    router.vm.box = "higebu/vyos"
    router.vm.network "private_network",
                       ip: "192.168.205.1",
                       netmask: "255.255.255.0",
                       auto_config: true
  end
  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--ostype", "Debian_64"]
    v.cpus = 1
    v.memory = 512
  end
  config.vm.host_name = "bgp-router"
end
